#!/bin/sh

set -o errexit

gofmt_output=$(gofmt -l .)
if ! test -z "$gofmt_output"; then
    echo unformatted files: $gofmt_output
    echo 'run `go fmt <file>` to format'
    exit 1
fi

golangci-lint run

go test -v ./...
